site_name: System Design Notes
site_url: https://abhijit25mishra.github.io/System-Design-Notes
docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand        # Enables collapsible folders
    - navigation.sections      # Groups items under headings
    - navigation.tabs          # Adds top-level tabs
    - navigation.tabs.sticky   # Keeps tabs visible when scrolling
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - group:
      enabled: true
      plugins:
        - search
        - awesome-pages
